# Generated by Django 4.2 on 2026-06-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.CharField(default='AI/ML Engineer', max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('total_candidates', models.IntegerField(default=0)),
                ('duration_sec', models.FloatField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('submission_csv', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('stats_json', models.TextField(blank=True, default='{}')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('candidate_id', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('raw_score', models.FloatField(default=0)),
                ('reasoning', models.TextField()),
                ('profile_json', models.TextField(default='{}')),
                ('components_json', models.TextField(default='{}')),
                ('signals_json', models.TextField(default='{}')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='ranker.rankingrun')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
