# Generated by Django 4.2 on 2026-06-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_key', models.CharField(help_text='e.g. phd, m.tech, mba', max_length=50, unique=True)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('tier', models.IntegerField(choices=[(1, 'Tier 1 (High Priority)'), (2, 'Tier 2 (Medium Priority)'), (3, 'Tier 3 (Low Priority)')])),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_weight', models.FloatField(default=0.4)),
                ('title_career_weight', models.FloatField(default=0.25)),
                ('experience_weight', models.FloatField(default=0.15)),
                ('education_weight', models.FloatField(default=0.1)),
                ('signals_weight', models.FloatField(default=0.1)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='TierWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_key', models.CharField(help_text='e.g. tier_1, tier_2', max_length=50, unique=True)),
                ('weight', models.FloatField()),
            ],
        ),
    ]
